# Configuration file for winding machine

serial:
  port: "/dev/ttyACM0"
  baudrate: 115200

motor:
  M0: 
    wind_range_end: -6.5
    wind_range_start: -12.5
    end_to_zero: 6.0
    velocity: 5.0
  M1:
    zero: -0.01
    end_to_rotating_position: 4.0
    velocity: 5.0
  M2:
    zero: 0.0
    angle_to_prevent_collision: 1.0
    velocity: 20.0
  M3:
    pull_wire_torque: 0.2
    wind_torque: 0.08
    velocity: 5.0

winding:
  # production
  turns_per_slot: 75
  starts_at: 0
  winding_config: "AaAabBbBCcCcaAaABbBbcCcC" # 24n22p
  dont_move_m3: false # true for debugging, false for production