# Configuration file for winding machine

serial:
  port: "/dev/ttyACM0"
  baudrate: 115200

motor:
  M0: 
    wind_range_end: -14
    wind_range_start: -21
    end_to_zero: 6.0
  M1:
    zero: -0.05
    end_to_rotating_position: 6.0
  M2:
    zero: -1.4
    angle_to_prevent_collision: 1.0
  M3:
    zero: 0.0
    pull_wire_torque: 0.2
    wind_torque: 0.0
  M4:
    zero: 0.0
    grab_wire_position: 0.28
    catch_wire_position: -0.3
    # catch_wire_position: -0.6

winding:
  # 24n22p
  slot_pairs: 12
  # production
  turns_per_slot: 75
  starts_at: 0
  dont_move_m3: false # true for debugging, false for production
  


logging:
  level: "INFO"
  file: "winding_machine.log"