# Configuration file for winding machine

serial:
  port: "/dev/ttyACM0"
  baudrate: 115200

motor:
  M0: 
    wind_range_end: -6
    wind_range_start: -13
    end_to_zero: 6.0
  M1:
    zero: 0.02
    end_to_rotating_position: 4.0
  M2:
    zero: 2.55
    angle_to_prevent_collision: 1.0
  M3:
    zero: 0.0
    pull_wire_torque: 0.2
    wind_torque: 0.08

winding:
  # 24n22p
  slot_pairs: 12
  # production
  turns_per_slot: 75
  starts_at: 0
  dont_move_m3: false # true for debugging, false for production
  


logging:
  level: "INFO"
  file: "winding_machine.log"